***************** NOMBRE *******************
fmod NATURAL is

***************** CONJUNTOS ****************
   protecting BOOL .
   sort N .
   sort NoN .
   subsort NoN < N .

***************** SINTAXIS *****************
   op cero : -> N .
   op sucesor : N -> N .
   op suma : N N -> N .
   op esCero : N -> Bool .
   op esIgual : N N -> Bool .
   op esDistinto : N N -> Bool .
   op producto : N N -> N . 
   op potencia : N N -> N .
   op cuadrado : N -> N .
   op factorial : N -> N .
   op predecesor : N -> N .
   op resta : N N -> N .
   op diferencia : N N -> N .
   op difUno : N N -> Bool .

   op NODEFINIDO : -> NoN .
   op INFINITO : -> NoN .
   op NEGATIVO : -> NoN .

***************** SEMANTICA ****************
   var n m : N .
   
   eq suma(cero, n) = n .
   eq suma(sucesor(m), n) = sucesor(suma(m, n)) .

   eq esCero(cero) = true .
   eq esCero(sucesor(n)) = false .
   
   eq esIgual(cero, n) = esCero(n) .
   eq esIgual(sucesor(n), cero) = false .
   eq esIgual(sucesor(n), sucesor(m)) = esIgual(n, m) .

   eq esDistinto(n, m) = not esIgual(n, m) .

   eq producto(cero, n) = cero . 
   eq producto(sucesor(n), m) = suma (m, producto (n, m )) .

   eq potencia(cero, cero) = NODEFINIDO .
   eq potencia(cero, n) = cero .
   eq potencia(n, cero) = sucesor(cero) .
   eq potencia(n, sucesor(m))= producto(n, potencia(n, m)) .

   eq cuadrado(cero) = cero .    *** 0^2
   eq cuadrado(n) = potencia(n, sucesor(sucesor(cero))) .   *** n^2

   eq factorial(cero) = sucesor(cero) .   *** 0! = 1
   eq factorial(sucesor(n)) = producto(sucesor(n), factorial(n)) .

   eq predecesor(cero) = NEGATIVO .
   eq predecesor(sucesor(n)) = n .

   eq resta(n, cero) = n .
   eq resta(cero, sucesor(m)) = NEGATIVO .
   eq resta(sucesor(n), sucesor(m)) = resta(n, m) .

   eq diferencia(n, cero) = n .
   eq diferencia(cero, m) = m .
   eq diferencia(sucesor(n), sucesor(m)) = diferencia(n, m) .

   eq difUno(cero, cero) =  true .
   eq difUno(sucesor(cero), cero) =  true .
   eq difUno(cero, sucesor(cero)) =  true .
   eq difUno(sucesor(sucesor(n)), cero) = false .
   eq difUno(cero, sucesor(sucesor(m))) = false .
   eq difUno(sucesor(n), sucesor(m)) = difUno(n, m) .

endfm
